drop table if exists generation_usage;
drop index if exists generation_jobs_retry_of_idx;
drop index if exists generation_jobs_billing_due_idx;
drop index if exists generation_jobs_billing_trace_idx;
alter table generation_jobs drop column if exists billing_meter_usage;
alter table generation_jobs drop column if exists billing_attempt_count;
alter table generation_jobs drop column if exists billing_error;
alter table generation_jobs drop column if exists billing_started_at;
alter table generation_jobs drop column if exists billing_next_check_at;
alter table generation_jobs drop column if exists billing_last_checked_at;
alter table generation_jobs drop column if exists billing_status;
alter table generation_jobs drop column if exists billing_trace_id;
alter table generation_jobs drop column if exists retry_of_job_id;
drop index if exists users_status_created_idx;
alter table users drop column if exists updated_at;
alter table users drop column if exists last_login_at;
alter table users drop column if exists disabled_by;
alter table users drop column if exists disabled_at;
alter table users drop column if exists disabled_reason;
alter table users drop column if exists account_status;
